theme: jekyll-theme-minimal
title: Michelle Wan
description: Hello! I'm Michelle (she/her), and I'm a third-year PhD student with the AI4ER CDT at the University of Cambridge. 
logo: /images/headshot.jpeg
