theme: jekyll-theme-minimal
title: Michelle Wan
description: Hello! I'm Michelle, and I'm a first-year PhD student with the [AI4ER CDT](https://ai4er-cdt.esc.cam.ac.uk) at the University of Cambridge.
logo: /images/headshot.jpeg
